openapi: 3.0.3
info:
  title: Employee Service API
  version: 1.0.0
  description: API for managing employee profiles in the onboarding system.
servers:
  - url: http://localhost:3001
paths:
  /api/employees:
    post:
      summary: Register a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john@example.com
                startDate:
                  type: string
                  format: date
                  example: 2025-05-01
              required:
                - name
                - email
                - startDate
      responses:
        '201':
          description: Employee registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        startDate:
          type: string
          format: date
        status:
          type: string
          enum: [PENDING, ACTIVE, INACTIVE, TERMINATED]
